<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MailChimpIFrame</name>
   <tag></tag>
   <elementGuidId>59ef9248-2e79-4cf0-bfb9-c7625f2794e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      <webElementGuid>618eb288-7312-4263-be9b-391d1467ef6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
