<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>0f743ddc-d958-4f73-a626-f958a0a519d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/table/tbody/tr/td[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e5563d9-cf02-4fb9-abf3-3f941a54987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-menu-item</value>
      <webElementGuid>5d806884-fb4f-4fbc-83fc-fed393e93d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {target: $col.getTarget($action()), href: $action().href}, text: $action().label, click: $col.getActionHandler($action())</value>
      <webElementGuid>1e3a6668-6648-4b5c-ae26-5e9735111b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-repeat-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b8c163a-1576-4c02-89ce-a93ce34a11e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>442f1b8d-a550-4c6a-a85f-c164adf793fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/</value>
      <webElementGuid>1a99e479-1370-4d86-a457-49dc15e2bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>4dfe2624-8d1e-446a-8b05-ceaa32eab604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;admin__data-grid-outer-wrap&quot;]/div[@class=&quot;admin__data-grid-wrap&quot;]/table[@class=&quot;data-grid data-grid-draggable&quot;]/tbody[1]/tr[@class=&quot;data-row&quot;]/td[@class=&quot;data-grid-actions-cell&quot;]/a[@class=&quot;action-menu-item&quot;]</value>
      <webElementGuid>6509033d-4fc4-4a7f-8732-a719787ff69d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/table/tbody/tr/td[9]/a</value>
      <webElementGuid>41f7bca6-99fb-4fe2-8f44-fb8943d470f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>0a41c3cc-19ff-4eae-9f4f-828c51245b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queued'])[1]/following::a[1]</value>
      <webElementGuid>716b0e2a-c6d4-40db-9bd3-4dc625a838a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customer_login_otp'])[1]/following::a[1]</value>
      <webElementGuid>078ac4eb-6990-41a1-8e6f-49abe7397936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifonic'])[2]/preceding::a[1]</value>
      <webElementGuid>76f5d15d-f81b-43b9-b4e6-9d370beceed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>2a3f6c35-ff7a-42cb-93ef-c6c5c4b8e451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/')]</value>
      <webElementGuid>1d9a4e0c-0147-4178-aa42-f6010f1f8a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>d99473d9-7a52-4ff2-b6e6-5e23ac4f8049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>ca43a57b-730e-4dfa-88dc-5371a40a262f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
