<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>a9834529-b555-4e3a-b79b-902e02150fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/table/tbody/tr/td[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51d286c9-f778-48f3-9429-a0ae5b61ade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-menu-item</value>
      <webElementGuid>39e00f09-0e61-47a0-8084-ae63fec3d177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {target: $col.getTarget($action()), href: $action().href}, text: $action().label, click: $col.getActionHandler($action())</value>
      <webElementGuid>a6e5a3bb-3c13-4087-a3a9-cffabb8c8ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-repeat-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b25aba36-fdde-48fb-b477-b6f2a4a5be26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6057da89-3d4f-4416-ac18-e35ff3a74b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/</value>
      <webElementGuid>857b677b-a720-4526-8e91-7f8abcc3505e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>81009dad-48c6-48af-b68d-8e5f4e123dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;admin__data-grid-outer-wrap&quot;]/div[@class=&quot;admin__data-grid-wrap&quot;]/table[@class=&quot;data-grid data-grid-draggable&quot;]/tbody[1]/tr[@class=&quot;data-row&quot;]/td[@class=&quot;data-grid-actions-cell&quot;]/a[@class=&quot;action-menu-item&quot;]</value>
      <webElementGuid>a8fde362-3419-45c4-808e-0193cf760d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/table/tbody/tr/td[9]/a</value>
      <webElementGuid>0fe16e2d-c83d-4721-bd8b-3b4d2a3df972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>813ef401-d896-4b6d-8bd7-29266947a6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queued'])[1]/following::a[1]</value>
      <webElementGuid>adde2021-e1ed-4a0f-b716-988f573cd677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customer_login_otp'])[1]/following::a[1]</value>
      <webElementGuid>7fd4e449-8e42-46b8-b455-599738b0b809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifonic'])[2]/preceding::a[1]</value>
      <webElementGuid>0d80ac46-8a69-4ab5-96a1-54c1415dae49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>18b3e59d-21e7-42db-81ec-3f9152ce4251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/')]</value>
      <webElementGuid>99572254-e940-43f1-853f-d686f07309d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>31d0460b-a82a-4c24-b1b7-c68cef29aa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://backend.ajstore.com/admin_15cfht/smsprofile/smsprofilelog/view/entity_id/51490/key/af6ef1871104247a9b91cbebafa1f75e79085a3faebebe7451a8819fc1ab2059/' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>a55c5783-59dc-44fd-a86d-0b5e93ba0969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
