<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mega menu</name>
   <tag></tag>
   <elementGuidId>63c02c2d-8cdc-4873-9c2c-9db880b5124c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='styles_mainMegaMenuSpaceBetween__DdNTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6082917f-c096-4162-99bb-aa57ddb716c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674720098182</value>
      <webElementGuid>3614024f-6ce6-4dc4-bc4f-88aa48547e91</webElementGuid>
   </webElementProperties>
</WebElementEntity>
