<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipmentMethodsList</name>
   <tag></tag>
   <elementGuidId>26d6d03a-3a74-4b27-a1ca-b89691842638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      <webElementGuid>dd8f2729-2747-4374-bb94-1cde38822afe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
