<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>beb1cf92-6946-4fbb-834f-d3a796295351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.megaMenuItem-megaMenuLink-12G</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[3]/div/nav/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>719ade1e-1ca3-4255-b166-c7d32847ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>megaMenuItem-megaMenuLink-12G</value>
      <webElementGuid>7b1a0109-8df1-4946-8a8f-873e3e21be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/women/pajamas.html</value>
      <webElementGuid>08b84afe-6ac8-4aae-88ff-b035f72dfca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>البيجاما</value>
      <webElementGuid>35e9fa18-682e-4c14-b00a-a96aed03382b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;megaMenu-wrapper-2rA&quot;]/div[@class=&quot;megaMenu-container-2FL&quot;]/nav[@class=&quot;megaMenu-megaMenu-2LU&quot;]/div[@class=&quot;megaMenuItem-root-HSc&quot;]/a[@class=&quot;megaMenuItem-megaMenuLink-12G&quot;]</value>
      <webElementGuid>920e1f82-6dfd-48d2-9848-d05da4f9830a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[3]/div/nav/div/a</value>
      <webElementGuid>b9c69f21-11ee-410b-855a-b0fc914c2a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'البيجاما')]</value>
      <webElementGuid>0dba502f-92f0-4546-a40a-38748193a1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='البحث عن منتج'])[1]/following::a[1]</value>
      <webElementGuid>c88c9a29-471c-4fc8-8c99-2412f07d3daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نسائي'])[1]/following::a[2]</value>
      <webElementGuid>aab9db6a-28f4-45cf-b1bf-ae44fdd94329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نسائي'])[2]/preceding::a[1]</value>
      <webElementGuid>923d479d-67b7-45c8-b35a-1fce071298ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بناتي شبابي'])[1]/preceding::a[2]</value>
      <webElementGuid>44bca568-262c-4804-8657-6319b1abe0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='البيجاما']/parent::*</value>
      <webElementGuid>bf16f324-43f7-4fea-acba-2d3bfcc23983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/women/pajamas.html')]</value>
      <webElementGuid>84ab7ef9-9e87-4748-bbf3-ea9b8ce20216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a</value>
      <webElementGuid>d4210bed-d197-4125-9ec3-2739784859e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/women/pajamas.html' and (text() = 'البيجاما' or . = 'البيجاما')]</value>
      <webElementGuid>adb19536-e638-47ae-8695-a620b0ad7751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
