<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__image-image-2gD image-loaded-SHk image_3b67db</name>
   <tag></tag>
   <elementGuidId>16a589dc-c0e5-4276-8962-6edf3431b39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image-image-2gD.image-loaded-SHk.image-loadedRtl-sS7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fd0bc0dd-d05e-44bc-a7c1-6566acad4bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0739ba79-d9a3-4e38-a5d3-448219c748ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>e1c0869a-7102-4dea-8586-e0d8b4918c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image-2gD image-loaded-SHk image-loadedRtl-sS7</value>
      <webElementGuid>280444d4-a76a-419f-81cc-a3bc292b10fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>dffd403c-b3b8-4cfd-85df-684d4de87333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logo-8QT.png</value>
      <webElementGuid>4525b825-9301-4df2-987b-99fe50d6f12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>e5e39863-dcfa-40da-99bb-ab84dcc2e1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;middleHeaderBar-root-3ns middleHeaderBar-close-2Ut middleHeaderBar-root-3ns&quot;]/div[@class=&quot;middleHeaderBar-content-_nW&quot;]/a[@class=&quot;middleHeaderBar-logoWrapper-1WY&quot;]/div[@class=&quot;image-root-Qpm
        image-container-_fN&quot;]/img[@class=&quot;image-image-2gD image-loaded-SHk image-loadedRtl-sS7&quot;]</value>
      <webElementGuid>8ed4dc0b-4754-4032-a8a5-de4c2bb3f5f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      <webElementGuid>1cf97a3c-ef91-42f4-8b2f-637281b0629c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logo'])[2]</value>
      <webElementGuid>ed1c8906-be15-4396-9d36-ad9e43634e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>f0a33a14-0626-4c38-88a8-7a86f1881fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo' and @src = '/logo-8QT.png']</value>
      <webElementGuid>0a22d43c-90f9-4ee3-8c26-b35e174422c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
