<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__image-image-2gD image-loaded-SHk image_3b67db</name>
   <tag></tag>
   <elementGuidId>09b83fce-e35d-4ce9-8fc4-ab9b4aed3c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image-image-2gD.image-loaded-SHk.image-loadedRtl-sS7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b0fb5a6-9106-49c8-940d-b628ce3739ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>80d1dd93-d545-4589-b7d3-08dbc0817772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>9c5e3dd5-2339-461b-9cd0-5023e72cbe75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image-2gD image-loaded-SHk image-loadedRtl-sS7</value>
      <webElementGuid>79d3d2f3-1991-470e-bd9b-32f2e8f666ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>debcfc73-eb31-4746-9fa2-1c8ebf545cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logo-8QT.png</value>
      <webElementGuid>5893cd84-ec15-4987-ae96-0678d7bf4de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>80739ef6-9890-43b4-9856-f0bb80d3fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;middleHeaderBar-root-3ns middleHeaderBar-close-2Ut middleHeaderBar-root-3ns&quot;]/div[@class=&quot;middleHeaderBar-content-_nW&quot;]/a[@class=&quot;middleHeaderBar-logoWrapper-1WY&quot;]/div[@class=&quot;image-root-Qpm
        image-container-_fN&quot;]/img[@class=&quot;image-image-2gD image-loaded-SHk image-loadedRtl-sS7&quot;]</value>
      <webElementGuid>5387d4d0-f46a-4b2b-847b-ab9b6b907d27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      <webElementGuid>593c0ae7-8ccf-4bb9-855a-f3ae1bffe602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logo'])[2]</value>
      <webElementGuid>6e20d067-f539-422d-8c1d-a787243b8ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>8049e13c-dc37-4f75-9d40-e81b87265a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo' and @src = '/logo-8QT.png']</value>
      <webElementGuid>e150f604-468e-44b6-8dfa-f87cb697e322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
