<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__image-image-2gD image-loaded-SHk image_3b67db</name>
   <tag></tag>
   <elementGuidId>008acc06-2178-40c4-a0a4-b255587c3219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-image-2gD.image-loaded-SHk.image-loadedRtl-sS7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63d12d95-1206-4b72-bae3-8981ced92be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a18b37b1-0bdc-4f2e-854c-44cbe05610c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>2b9cdccb-0d92-4036-9de5-401356955d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image-2gD image-loaded-SHk image-loadedRtl-sS7</value>
      <webElementGuid>877c19d2-af6b-4541-a156-8b7787792d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>9d28a176-6270-4f55-9ed0-79bc0f48bddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logo-8QT.png</value>
      <webElementGuid>e8042a3b-c81a-44ba-ba50-0cad6ddb8711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>fcb8a826-ef03-4850-8cc8-45c84921ff62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;middleHeaderBar-root-3ns middleHeaderBar-close-2Ut middleHeaderBar-root-3ns&quot;]/div[@class=&quot;middleHeaderBar-content-_nW&quot;]/a[@class=&quot;middleHeaderBar-logoWrapper-1WY&quot;]/div[@class=&quot;image-root-Qpm
        image-container-_fN&quot;]/img[@class=&quot;image-image-2gD image-loaded-SHk image-loadedRtl-sS7&quot;]</value>
      <webElementGuid>09826a95-9207-40da-a533-84392f809c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      <webElementGuid>2ad5e7e6-8dfb-4941-8a9a-53fa2e49a4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logo'])[2]</value>
      <webElementGuid>75ab1111-7524-4768-9dd8-c2a9545fdaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>4973b8c6-6141-40e8-acc5-d805981ed538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo' and @src = '/logo-8QT.png']</value>
      <webElementGuid>2aba01e5-51e7-4ec4-b6ca-76bb5e4db977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
