<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sign Out</name>
   <tag></tag>
   <elementGuidId>c926edd8-5a2b-459f-ae01-bbcdae636f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='تسجيل الخروج' or normalize-space(.)='Sign Out']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e683ff46-ea45-4c0b-a24a-bdc7d4223e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>private-account-menu__sidebarTitle</value>
      <webElementGuid>a31a1ada-68c1-4893-99e2-1308b4ee2aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
      <webElementGuid>10ab6abe-706f-4e22-9adb-4c523d36114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main-page-content&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;styles_privateAccountPageContainer__EgAXB&quot;]/div[@class=&quot;styles_privateAccountMenuContainer__Zffje&quot;]/div[@class=&quot;private-account-menu&quot;]/button[@class=&quot;private-account-menu__itemV4&quot;]/div[@class=&quot;private-account-menu__titleV4&quot;]/div[1]/p[@class=&quot;private-account-menu__sidebarTitle&quot;]</value>
      <webElementGuid>80590c7a-c9a8-4610-ab17-c0aa77863a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[5]/div/div/div/div/button[9]/div/div/p</value>
      <webElementGuid>7fa00621-61b4-4fb7-8980-8688777ed54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account menu'])[1]/following::p[17]</value>
      <webElementGuid>4d4d043c-e723-44d2-9207-69e429c6b52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::p[25]</value>
      <webElementGuid>05268822-f152-4425-b0f4-985781272311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Azeez Saleh'])[1]/preceding::p[2]</value>
      <webElementGuid>b9f605de-7d2f-46f1-8a46-95e373a9d455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a.aldon@snaptec.co'])[1]/preceding::p[2]</value>
      <webElementGuid>2ab24e31-c37a-4f20-8382-26e3fa96216a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Out']/parent::*</value>
      <webElementGuid>873bf490-a51e-4832-b790-aeecd845dfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[9]/div/div/p</value>
      <webElementGuid>06d80dfa-95dd-4c2c-9daa-7dbcdaf2a1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sign Out' or . = 'Sign Out')]</value>
      <webElementGuid>b9d35943-183d-41d2-af09-4f459cdea370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
