name: CI FOR KATALON ENGINE
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '10.0.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Test Collections/SaaS/Regression on Production - Web browser" -apiKey="85154bfa-7201-47ab-891b-253ece8a3a85" -orgID=1714454 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'

    - name: Verify Report Path
      run: |
        echo "Listing report files..."
        dir "${{ github.workspace }}/Reports"
    - name: Upload Katalon Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: katalon-reports
        path: '${{ github.workspace }}/Reports'


        katalonc -noSplash -runMode=console -projectPath="C:\Users\Administrator\Documents\GitHub\Katalon-Framework\Automation-SaaS-main\Automation-SaaS-main.prj" -retry=0 -testSuiteCollectionPath="Test Suites/Test Collections/SaaS/Regression on Production - Web browser" -apiKey="85154bfa-7201-47ab-891b-253ece8a3a85" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true