<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>aaef10a6-395a-483e-9ede-5a9fc25d44b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='accountTabs']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.register-step > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5af49feb-4b7b-4039-aa19-3ed31d67eb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sa.blend.arabianoud.com/index.php?route=account/register</value>
      <webElementGuid>597df6ba-a202-443e-86a8-891730252d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>account</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>39fead2f-44fc-4177-94de-591692e68fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>91cfc5ca-97c0-41dd-9fdd-aaa0613daeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTabs&quot;)/li[@class=&quot;register-step&quot;]/a[1]</value>
      <webElementGuid>a89dc7ad-09a2-4a65-8502-2cdb12a42421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='accountTabs']/li[2]/a</value>
      <webElementGuid>ab575b2d-4477-4cbd-8946-570afbe7d1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>0c2ef4fa-0413-4ce2-8836-bb9d81f8b8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>c35fbe8e-98d7-4251-89ff-32b011b985bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with your email'])[1]/preceding::a[1]</value>
      <webElementGuid>3c56a292-f9e5-48f6-9b2c-322696e29434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saudi Arabia (‫المملكة العربية السعودية‬‎)'])[1]/preceding::a[1]</value>
      <webElementGuid>91c67b3f-aaee-45eb-b749-5debae654027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>69572d41-d768-4a80-a185-55d34ef8e6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sa.blend.arabianoud.com/index.php?route=account/register')]</value>
      <webElementGuid>5ac3f843-8158-4353-9117-302919a9626b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>5ea03609-d1ef-42ed-b19d-be1b0d6feca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sa.blend.arabianoud.com/index.php?route=account/register' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>8fd0de40-2b9a-4404-a491-1a988b1ddd75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
