<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0c6b53d5-f944-4a2f-922a-9e32be3e8036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;myaccount&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div/div[2]/div/div/div[3]/div/div/a/span/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e41984f2-6f68-4639-98fe-671edf5e5466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>myaccount</value>
      <webElementGuid>4a793e62-4a40-4e94-a4e3-803fc37a7f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://release.thenineten.co/media/global/logo/websites/14/Icon_1_.png 1x, https://release.thenineten.co/media/global/logo/websites/14/Icon_1_.png 2x</value>
      <webElementGuid>797474c5-4377-4065-8739-071365785aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://release.thenineten.co/media/global/logo/websites/14/Icon_1_.png</value>
      <webElementGuid>a2285a8d-659c-46f0-8cbf-67c0c46b9652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>76951581-bb99-4105-bbb4-583dd8440d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>46ed35ac-7e2e-47dc-95fb-609f9b373248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_headerContainer__b9Hm9&quot;]/div[@class=&quot;header v5&quot;]/div[@class=&quot;main-header&quot;]/div[@class=&quot;main-header__content&quot;]/div[@class=&quot;desktop-content&quot;]/div[@class=&quot;styles_rightContent__23dTx&quot;]/div[@class=&quot;styles_buttonGroup__9sviK&quot;]/div[@class=&quot;header__item styles_profilebtn__D9Yyh&quot;]/a[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;image-container&quot;]/span[1]/img[1]</value>
      <webElementGuid>e1839c38-472f-4622-becf-b2f29bf77cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div[2]/div/div/div[3]/div/div/a/span/span/img</value>
      <webElementGuid>39939235-7dde-47c6-992d-3d26e63883b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='myaccount']</value>
      <webElementGuid>0a5b1063-7165-40bd-a9e1-5111d4535e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span/img</value>
      <webElementGuid>76ee01b7-492c-4380-850f-08488451abac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'myaccount' and @src = 'https://release.thenineten.co/media/global/logo/websites/14/Icon_1_.png']</value>
      <webElementGuid>551a0f9a-a287-4606-aea4-33c500d49d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
