<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipmentMethodsList</name>
   <tag></tag>
   <elementGuidId>2660a6af-8774-4877-bdac-0b3aa315ee8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      <webElementGuid>d064a19b-c50d-4b29-b78e-46225a998880</webElementGuid>
   </webElementProperties>
</WebElementEntity>
