<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MailChimpIFrame-Mobile</name>
   <tag></tag>
   <elementGuidId>a2203cb0-7b89-4cb4-a091-0d412fd91bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@data-dojo-attach-point=&quot;iframeBannerContainer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@data-dojo-attach-point=&quot;iframeBannerContainer&quot;]</value>
      <webElementGuid>8111d3c8-7ff0-4059-bd69-80c5a5eb9795</webElementGuid>
   </webElementProperties>
</WebElementEntity>
