<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I wish to subscribe to the   newslett_4c072b</name>
   <tag></tag>
   <elementGuidId>a370f20c-fe10-4613-a3ec-6833c089b531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newsletter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newsletter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ebff034-b75c-42dd-a447-d0118dd0f8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b52f3889-b8fb-4a7d-8514-53b6d2100074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox</value>
      <webElementGuid>b22c262c-db26-49d1-865b-afd6adcf40fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>6b799fcd-2fd4-4f34-9c9d-ec4a800a168f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bafb9cbf-1139-409e-a627-2f2083aa20d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>3cb65601-84de-4cdd-8aba-43e5a7c014c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newsletter&quot;)</value>
      <webElementGuid>95a32ab2-b468-4ab4-a45c-055881d8317d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newsletter']</value>
      <webElementGuid>8b9c636d-3256-4bda-ba7e-35b9fd1bff27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_register']/div[13]/div/label/input</value>
      <webElementGuid>dcc7df9f-4ced-484b-a3ef-87e6022fb7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/label/input</value>
      <webElementGuid>bb9495cc-b0cc-40a4-966f-c454687179d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'newsletter' and @id = 'newsletter']</value>
      <webElementGuid>b7917c01-71a8-4d28-a8f4-6b1a63f197c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
