<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>4297b342-c203-4970-97ad-9b4027560f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ca5179da-bfb4-4bdc-b2f7-51b5c833925b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>index.php?route=account/register&amp;popup=register</value>
      <webElementGuid>3960c036-bb7b-49f3-96de-dc887f62d976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f44ca1ea-ddf7-4dc9-a562-606a3ed3ba17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>541</value>
      <webElementGuid>a11967c4-2dc2-4190-85f7-98a15675548f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fee412a0-2c42-4b66-bafd-a1c178b43e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.height = this.contentWindow.document.body.offsetHeight; $(this).prev('.journal-loading').fadeOut();</value>
      <webElementGuid>08c51170-48fe-4432-ba25-3490097858bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop win chrome chrome112 webkit oc30 is-guest route-common-home store-0 skin-1 desktop-header-active compact-sticky mobile-sticky no-currency no-compare layout-1 flexbox no-touchevents popup-open popup-center&quot;]/body[1]/div[@class=&quot;popup-wrapper popup-register&quot;]/div[@class=&quot;popup-container&quot;]/div[@class=&quot;popup-body&quot;]/div[@class=&quot;popup-inner-body&quot;]/iframe[1]</value>
      <webElementGuid>6e5855e3-27eb-4def-8eb4-91184c428b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>66fc283c-6b94-48a5-b9ba-374f75bffd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'index.php?route=account/register&amp;popup=register']</value>
      <webElementGuid>c5a915e7-c5e0-47d6-abd4-aa4584638a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
