<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Register</name>
   <tag></tag>
   <elementGuidId>af8255fd-e073-454f-80ec-510742410b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.top-menu-item-11 > a > span.links-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb08a6eb-3c2b-45cc-af98-1a5961f2cf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>links-text</value>
      <webElementGuid>de954b48-fc21-4317-b087-4a654efdc57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>e40bf4f3-be7a-42a8-a08e-50ffc6149826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop win chrome chrome112 webkit oc30 is-guest route-common-home store-0 skin-1 desktop-header-active compact-sticky mobile-sticky no-currency no-compare layout-1 flexbox no-touchevents&quot;]/body[1]/div[@class=&quot;site-wrapper&quot;]/header[@class=&quot;header-compact&quot;]/div[@class=&quot;header header-compact header-sm&quot;]/div[@class=&quot;top-bar navbar-nav&quot;]/div[@class=&quot;third-menu&quot;]/div[@class=&quot;top-menu top-menu-14&quot;]/ul[@class=&quot;j-menu&quot;]/li[@class=&quot;menu-item top-menu-item top-menu-item-9 dropdown drop-menu open animating&quot;]/div[@class=&quot;dropdown-menu j-dropdown&quot;]/ul[@class=&quot;j-menu&quot;]/li[@class=&quot;menu-item top-menu-item-11&quot;]/a[1]/span[@class=&quot;links-text&quot;]</value>
      <webElementGuid>d2d010ee-16c6-459f-86b7-e33cff17f8df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::span[1]</value>
      <webElementGuid>7fd9851e-d39e-4ee6-a7a8-b30c7e737df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login / Register'])[1]/following::span[2]</value>
      <webElementGuid>5a2093ad-da13-4523-8361-ba39c06e7cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Your Wishlist'])[1]/preceding::span[1]</value>
      <webElementGuid>186f6433-ef32-4e97-9c7b-cc1fe76bf61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>465b4ecb-eb5a-4529-9722-ab899e51fa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a/span</value>
      <webElementGuid>6014350c-cc81-4b22-a4c5-d95b345c1e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>bc4a7380-1be4-4310-918e-adfef0bfe94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
