<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TamaraProceedButtonPage2</name>
   <tag></tag>
   <elementGuidId>a62fd0a2-92fb-4aa1-8a29-b687fb9f52ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,&quot;confirmation-otp-submit-button&quot;)]//span[contains(text(),&quot;المتابعة&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
