<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <elementGuidId>c83d9d86-3b76-4b34-a8e6-de53183cf110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='core-input-button-group input search-product-input'] |//div [starts-with(@class,'styles_searchBox___')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ca74a6c4-c956-4db9-b80b-c908d03a4eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674658486391</value>
      <webElementGuid>d9c387a1-e089-4313-bc46-670ee2e35501</webElementGuid>
   </webElementProperties>
</WebElementEntity>
