<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foundsRecord</name>
   <tag></tag>
   <elementGuidId>ea318b18-6aed-4a97-91a3-e9b8a62527ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[starts-with(@class,'styles_listCardIllustrating__')]/div[starts-with(@class,'styles_cardIllustratingItem__')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(@class,&quot;styles_recordsText&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[starts-with(@class,'styles_listCardIllustrating__')]/div[starts-with(@class,'styles_cardIllustratingItem__')]</value>
      <webElementGuid>288d3626-5f73-4e56-9e9b-3eeb2eb7ea44</webElementGuid>
   </webElementProperties>
</WebElementEntity>
