<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumberOfItem</name>
   <tag></tag>
   <elementGuidId>51991fca-e672-42fb-ad8f-dba63a9fc821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table-with-scroll']/following-sibling::div//div[contains(@class,'styles_dropdown')]/select/option</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[starts-with(@class,'styles_listCardIllustrating__')]/div[starts-with(@class,'styles_cardIllustratingItem__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[starts-with(@class,'styles_listCardIllustrating__')]/div[starts-with(@class,'styles_cardIllustratingItem__')]</value>
      <webElementGuid>79960c32-dd27-42a2-9135-7a05d43c966f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
