<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpecificPageLink</name>
   <tag></tag>
   <elementGuidId>b8136ff8-f92d-400c-b8bb-6a77f2191e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[contains(@class,&quot;styles_pageContainer&quot;)]/li[contains(@class,&quot;styles_pageItem__&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
