<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MailChimpIFrame</name>
   <tag></tag>
   <elementGuidId>71a15645-83e4-40e5-b2e3-6ac0675eaae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      <webElementGuid>a066bee0-d851-4e6e-b646-2bfe4956e3dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
