<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spinner</name>
   <tag></tag>
   <elementGuidId>12579f38-0a05-41af-b76e-27b612e0b997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='indicator__icon-root']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='indicator__icon-root']</value>
      <webElementGuid>4ece9827-3389-4b40-9540-1dd2edb6efb3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
