<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastItemPrice</name>
   <tag></tag>
   <elementGuidId>2bd1e633-f253-43d3-97cf-5691d32895bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[starts-with(@class,'styles_footer__')]//preceding::div[starts-with(@class,'styles_subtotal__')][1]/span/span[@dir='rtl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[starts-with(@class,'styles_footer__')]//preceding::div[starts-with(@class,'styles_subtotal__')][1]/span/span[@dir='rtl']</value>
      <webElementGuid>29d077d9-471b-4cf3-9bce-38b630eb2aa8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
