<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BottomMenu-Mobile</name>
   <tag></tag>
   <elementGuidId>0aafbe8c-2102-4f30-8c43-ecbb55eb58ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,&quot;bottomTab-root-&quot;)]/div[contains(@class,&quot;bottomTab-bottomTab-&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
