<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StoreSelect-Mobile</name>
   <tag></tag>
   <elementGuidId>1b36d646-188e-4f3c-9d48-ba2de78384f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,&quot;bottomTab-bottomTab-&quot;)]//span[text()=&quot;إعدادات&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
