<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastName</name>
   <tag></tag>
   <elementGuidId>90aabe5d-c07e-4c53-bfea-f811701c30a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='lastName']</value>
      <webElementGuid>453c9f93-da7c-4a44-948a-ef909bb0ba44</webElementGuid>
   </webElementProperties>
</WebElementEntity>
