<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fav</name>
   <tag></tag>
   <elementGuidId>8666877f-7621-4775-b740-37af8acebaf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='d-lg-flex d-none align-items-center']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>129085e1-4a4c-48ed-82a4-ef740a0ffe3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674658712670</value>
      <webElementGuid>0a5bf492-ebbb-4c8c-aae2-c834686f8ca4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
