<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Language</name>
   <tag></tag>
   <elementGuidId>d4b07ab3-c410-43dd-b017-fe29b6888517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='language-container']//*[@class='language-trigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>47b1a175-9b61-4109-a907-adeb7a5de2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674720503510</value>
      <webElementGuid>4fa8ad77-ff6c-4e0b-ad09-1509eaa1f249</webElementGuid>
   </webElementProperties>
</WebElementEntity>
