<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Language</name>
   <tag></tag>
   <elementGuidId>d4b07ab3-c410-43dd-b017-fe29b6888517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='language-container']//div[@id='languageTriggerDropdownMenuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>dc73f3fb-7d44-4c6c-94f9-280aa17dada8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674720503510</value>
      <webElementGuid>6645397b-0b41-43e5-805b-a04e61cc504e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
