<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Language</name>
   <tag></tag>
   <elementGuidId>d4b07ab3-c410-43dd-b017-fe29b6888517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='language-container']//span[@class='language-trigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0306b76c-d37a-4294-92b2-08b8974a4203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674720503510</value>
      <webElementGuid>2e3a0903-6616-4aa1-b441-32c08c8e369a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
