<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo</name>
   <tag></tag>
   <elementGuidId>99fc0e61-7d96-4a17-a640-02dc348c56ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@loading='eager']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee8be396-64b6-48e9-b76f-f0b939b534d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>5e870aaf-64b7-4a5c-afef-0a438cf09670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://performance.thenineten.co/media/logo/stores/13/header-logo-en_1.png</value>
      <webElementGuid>a9f6c116-81eb-410c-ab83-046a54c1c803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>837229b2-3eed-48ad-a7ed-60049f184d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_headerContainer__b9Hm9&quot;]/div[@class=&quot;header v5&quot;]/div[@class=&quot;main-header&quot;]/div[@class=&quot;main-header__content&quot;]/div[@class=&quot;desktop-content&quot;]/div[1]/a[@class=&quot;header__logo&quot;]/div[@class=&quot;styles_logoImage__eE8oT&quot;]/img[1]</value>
      <webElementGuid>c0f6e1ae-44fe-4d78-9a9c-0977c76608f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div[2]/div/div/div/a/div/img</value>
      <webElementGuid>6db30bef-54fa-4e73-a376-8709e9ad3e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>51fcc6f6-c12a-40ec-b37d-112b3bd13d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>45b99c04-32d3-45ad-8917-26ad6a96fde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://performance.thenineten.co/media/logo/stores/13/header-logo-en_1.png' and @alt = 'logo']</value>
      <webElementGuid>2bf5a55c-7ad6-489f-950f-67ce31587b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
