<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>5586c4bb-8a95-4989-978a-d8c97a26c414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.storeSwitcher-trigger-3Ud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4fafac4-eed6-4fcb-b4bd-c9d76217f03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>storeSwitcher-trigger-3Ud</value>
      <webElementGuid>1a36a03e-04ac-453d-8722-f9b27bf44216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>ad1c8500-0d27-48a5-b768-ca331691e8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>5eea3431-7583-4d87-ba9e-eb94236fb559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;topHeaderBar-root-qGV&quot;]/div[@class=&quot;topHeaderBar-content-1iy&quot;]/div[@class=&quot;topHeaderBar-infoSection-2l0&quot;]/div[@class=&quot;storeSwitcher-root-22r storeSwitcher-rootRtl-PAl&quot;]/button[@class=&quot;storeSwitcher-trigger-3Ud&quot;]</value>
      <webElementGuid>42b7a737-4895-42c5-a08b-083cb20e9899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div/div/div[2]/div[2]/button</value>
      <webElementGuid>3c9c8764-6f7b-4342-9ae1-f42210ad0818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمة العملاء:'])[1]/following::button[1]</value>
      <webElementGuid>c6ab3dfc-0c01-4c49-a6e0-51eb8e882ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الخروج'])[1]/following::button[1]</value>
      <webElementGuid>748d75c4-0bf8-4d74-8100-51c487c66dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العربية'])[2]/preceding::button[1]</value>
      <webElementGuid>bd4b97a7-6e20-45e3-957a-b0cd32c060d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[2]</value>
      <webElementGuid>5bfc08a3-0003-4776-bf38-a75379eb7ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='العربية']/parent::*</value>
      <webElementGuid>41e24959-12fc-4981-899c-e9ba0f0458cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>37bee845-e7ac-45d1-aa64-6b5d5a00ddda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'العربية' or . = 'العربية')]</value>
      <webElementGuid>2dc57002-db62-49ed-b543-77f8062d71af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
