<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>a8b5ed50-d559-4d0b-9d9b-72890efd53b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.storeSwitcher-trigger-3Ud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a1640df-6e46-4379-ae9a-e82e1d7e2abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>storeSwitcher-trigger-3Ud</value>
      <webElementGuid>5bf5e1fc-30f1-48d2-a0e3-dc582ba6df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>fd203139-efa3-4977-942d-2abf09c4cef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>العربية</value>
      <webElementGuid>27fd835d-174c-4b89-8512-371d80f0c8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;topHeaderBar-root-qGV&quot;]/div[@class=&quot;topHeaderBar-content-1iy&quot;]/div[@class=&quot;topHeaderBar-infoSection-2l0&quot;]/div[@class=&quot;storeSwitcher-root-22r storeSwitcher-rootRtl-PAl&quot;]/button[@class=&quot;storeSwitcher-trigger-3Ud&quot;]</value>
      <webElementGuid>9b7d80ca-06b2-452d-8e6f-259bce513971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div/div/div[2]/div[2]/button</value>
      <webElementGuid>e708ffb6-abaf-40b1-8e3b-1155af5eaa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمة العملاء:'])[1]/following::button[1]</value>
      <webElementGuid>3dcdfe1f-ccc1-4d29-bf9a-bbc106f28ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الخروج'])[1]/following::button[1]</value>
      <webElementGuid>9b3382a6-6514-4525-bf58-81c914c8069f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العربية'])[2]/preceding::button[1]</value>
      <webElementGuid>d8fb8618-a1c3-4617-912d-2d91b84eb419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[2]</value>
      <webElementGuid>0e9e9453-6006-494a-816c-ba819513e7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='العربية']/parent::*</value>
      <webElementGuid>7c5eb118-ae67-427d-8327-829018605d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>08b27dcf-3429-481e-8eb8-2fe012240692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'العربية' or . = 'العربية')]</value>
      <webElementGuid>3719b68f-a288-4764-b450-7221985d8326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
