<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0  ()  113.85</name>
   <tag></tag>
   <elementGuidId>431476ad-e478-4343-a44d-36f95ad71d1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-9']/div/div/div/div/div/div/div/div[13]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-slide.slick-active.slick-current > div > div.productBlock-customItemNoSize-cyc.item-root-1Qt > div.item-container-FZs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b71f2e05-2e1d-4a92-918e-014d110f45b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-container-FZs</value>
      <webElementGuid>82a36c76-0bd1-486b-afba-20285ba25a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة</value>
      <webElementGuid>8883ef85-af94-4e76-832b-a4549809b2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-9&quot;)/div[@class=&quot;tabProductBlock-tabItem-14y&quot;]/div[@class=&quot;productBlock-root-2Nd&quot;]/div[@class=&quot;sc-gtsrHT gfuSqG productBlock-wrapper-3JW&quot;]/div[@class=&quot;productBlock-slider-tok&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;productBlock-customItemNoSize-cyc item-root-1Qt&quot;]/div[@class=&quot;item-container-FZs&quot;]</value>
      <webElementGuid>6e6479e7-e6d0-4d20-a619-e47ef516ad8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-9']/div/div/div/div/div/div/div/div[13]/div/div/div</value>
      <webElementGuid>ff6a08e8-abc7-4d3a-98e2-083591f52413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أضف إلى السلة'])[12]/following::div[5]</value>
      <webElementGuid>5f5ccc50-5d20-477b-b7ab-1df4c270ae7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[12]/following::div[6]</value>
      <webElementGuid>22c371cb-be20-4bfc-afab-cdabbb6df9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div</value>
      <webElementGuid>42a0a7e7-8919-49e0-82c3-c7aaa387887a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة' or . = '0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة')]</value>
      <webElementGuid>03c6337b-4ceb-4a94-91d7-7594a17b5b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
