<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0056</name>
   <tag></tag>
   <elementGuidId>d0f324cb-97c3-493f-a08b-99ccb537eb4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.verificationPage-miniTitle-_s4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c3286c8-e892-45cc-9c19-68992b607cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verificationPage-miniTitle-_s4</value>
      <webElementGuid>f3a9abfb-fd89-4ebe-95dd-40cab0ba4372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00:56ارسال كود التحقق بعد </value>
      <webElementGuid>8e0a44ca-bdd3-447d-9a30-192986c50d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;verificationPage-container-3LA&quot;]/div[@class=&quot;verificationPage-root-2pJ verificationPage-verify-3VW&quot;]/div[3]/div[@class=&quot;verificationPage-miniTitle-_s4&quot;]</value>
      <webElementGuid>144f243f-c557-4378-86f2-88ff7c17ab2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[3]/div</value>
      <webElementGuid>4f76557b-41ce-4be7-98d6-a935f5ff022e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTP is expried.'])[1]/following::div[2]</value>
      <webElementGuid>ed52de69-6c72-4fba-bcb1-61c92d02cf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تابعنا عبر'])[1]/preceding::div[2]</value>
      <webElementGuid>50e7a6cb-ad4a-4653-b8e1-2c64b9f3710b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عجلان وإخوانه'])[1]/preceding::div[10]</value>
      <webElementGuid>632e7851-7bd9-4a72-891a-bc112552585a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ارسال كود التحقق بعد']/parent::*</value>
      <webElementGuid>23edcb41-8c4d-4d01-a51d-22185e34fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div</value>
      <webElementGuid>e7ceffc4-42c3-4f68-bf3b-1e21f046f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '00:56ارسال كود التحقق بعد ' or . = '00:56ارسال كود التحقق بعد ')]</value>
      <webElementGuid>6cfec44f-7a59-4d75-9434-1dfa9bf90339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
