<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3beb3ca0-97c4-4461-b289-c29378b17804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.middleHeaderBar-navWrapper-1c-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62c17075-f0ea-4b97-8d16-419275341707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>middleHeaderBar-navWrapper-1c-</value>
      <webElementGuid>e78fc523-89f6-4dde-8bf7-286e6356d344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>رجاليشبابيأطفالنسائي</value>
      <webElementGuid>e2e09743-5cd7-401f-a8e1-dc52fa2f2e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;middleHeaderBar-root-3ns middleHeaderBar-close-2Ut middleHeaderBar-root-3ns&quot;]/div[@class=&quot;middleHeaderBar-content-_nW&quot;]/div[@class=&quot;middleHeaderBar-navWrapper-1c-&quot;]</value>
      <webElementGuid>281d1aa4-0fa2-4e97-b5ef-d66a2bdc45e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[2]/div/div</value>
      <webElementGuid>a1fefc13-154b-4d8e-bf1e-432ee3e2613e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[3]</value>
      <webElementGuid>3da494bd-c00e-4508-80d8-b2bb44ad5d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='العربية'])[2]/following::div[3]</value>
      <webElementGuid>c50d26e9-e8c3-41ae-a6b0-b186cf8c3f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[2]/div/div</value>
      <webElementGuid>0978b064-3b02-4220-8c4c-2fcdce3f0bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'رجاليشبابيأطفالنسائي' or . = 'رجاليشبابيأطفالنسائي')]</value>
      <webElementGuid>7a2ca607-dbab-4bbd-aff1-6721d34e0009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
