<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>3f6f8a23-52f4-4f25-b863-9cf475c53c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tabProductBlock-headerTitle-2Eg.tabs-headerTitle-1C2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-tabs-8']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcb74d1b-59d8-4c36-a61b-1c3e47f73d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabProductBlock-headerTitle-2Eg tabs-headerTitle-1C2</value>
      <webElementGuid>6bf43809-ab52-4018-808b-7409eb9b71cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>منتجات الموسم</value>
      <webElementGuid>73d677c6-837f-4c34-90dc-26c5de7609a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-8&quot;)/div[@class=&quot;tabProductBlock-headerTitle-2Eg tabs-headerTitle-1C2&quot;]</value>
      <webElementGuid>152ac809-cf10-4223-8470-36cf8f083ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-tabs-8']/div</value>
      <webElementGuid>d1f1c91e-357e-4261-a56d-d7c0d6292236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عروض خاصة'])[1]/following::div[23]</value>
      <webElementGuid>244cb8ab-f802-4c34-85bd-d1c032a6dadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ثوب البيت الشتوي'])[1]/following::div[26]</value>
      <webElementGuid>1069bd04-61e4-4b0b-a267-5b02b517bd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاكثر مبيعاً'])[1]/preceding::div[1]</value>
      <webElementGuid>83f50647-49cf-4134-a46b-548ded43bfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المنتجات الجديدة'])[1]/preceding::div[2]</value>
      <webElementGuid>887634c8-7ea0-423a-8db5-ba869e057439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='منتجات الموسم']/parent::*</value>
      <webElementGuid>6e8f5a86-753c-4912-81c0-e72841d68734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>9ca1cf1f-f234-433c-8e83-a025edb8ce37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'منتجات الموسم' or . = 'منتجات الموسم')]</value>
      <webElementGuid>799d015b-f92c-4d65-8868-e2309777de19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
