<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__footer-paymentsLogo-CLu</name>
   <tag></tag>
   <elementGuidId>c383a98d-c823-45a8-9444-15affe0c6927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.footer-paymentsLogo-CLu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/footer/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02a88473-59d8-4765-acb9-c10132dd742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-paymentsLogo-CLu</value>
      <webElementGuid>ca36e935-dc32-40d1-9737-93efad2826bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/footer[@class=&quot;footer-root-39z&quot;]/div[@class=&quot;footer-main-1kk&quot;]/div[@class=&quot;footer-bottomFooter-2cn&quot;]/div[@class=&quot;footer-paymentsLogo-CLu&quot;]</value>
      <webElementGuid>cff99296-2255-47a2-a894-127c23499416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/footer/div/div[3]/div</value>
      <webElementGuid>cf5746f4-f2cb-4c94-b1db-a00d19e99906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسترجاع و الاستبدال'])[1]/following::div[7]</value>
      <webElementGuid>12da489b-fd1f-4076-b7fb-bd372c938e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سياسة الخصوصية'])[1]/following::div[7]</value>
      <webElementGuid>3ea743ff-ee1c-427e-bf57-4ff3bcdc6a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Store'])[1]/preceding::div[9]</value>
      <webElementGuid>dd1e016f-a738-4a99-8a75-2df7a7023f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Language'])[1]/preceding::div[12]</value>
      <webElementGuid>16a26422-390a-4f52-97cc-de6ff8ac8214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/div</value>
      <webElementGuid>69b63c64-16c6-4f02-a0dd-25ba5fa984a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
