<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>1a1160a6-df5e-401e-ba46-f4d0399bb7a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.subscribePage-root-33l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>103016e2-e735-40ea-aa79-2dd0ed50ca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subscribePage-root-33l</value>
      <webElementGuid>2317f5c8-becd-4189-932f-8a3dd26c28e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تابعنا عبر</value>
      <webElementGuid>0582001f-5517-4361-a600-3fc54ad86f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;subscribePage-root-33l&quot;]</value>
      <webElementGuid>a68a356f-c6c2-4910-8f3e-66af6ee6f831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[4]</value>
      <webElementGuid>b33a2711-15c4-427f-82f5-1defb94134c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأسعار شاملة الضريبة'])[1]/following::div[1]</value>
      <webElementGuid>4e71b1a5-afc3-4212-ab02-2de17849698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='وسائل دفع آمنة'])[1]/following::div[3]</value>
      <webElementGuid>c561142d-eb17-4529-a21e-8d494c09ccc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عجلان وإخوانه'])[1]/preceding::div[8]</value>
      <webElementGuid>3c957b67-3ae2-4568-8915-581509ca3759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[4]</value>
      <webElementGuid>5ed4fb04-d9bf-40de-81d8-3ae66c2d33cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'تابعنا عبر' or . = 'تابعنا عبر')]</value>
      <webElementGuid>7244b3ab-3d8e-47b1-928a-58f66f928437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
