<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__footer-paymentsLogo-CLu</name>
   <tag></tag>
   <elementGuidId>c383a98d-c823-45a8-9444-15affe0c6927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='footer-paymentsLogo-CLu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer-paymentsLogo-CLu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5762c4ad-7f7e-432d-82f1-afc077c5d49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-paymentsLogo-CLu</value>
      <webElementGuid>863054b3-5083-4150-8525-df7609f9f514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/footer[@class=&quot;footer-root-39z&quot;]/div[@class=&quot;footer-main-1kk&quot;]/div[@class=&quot;footer-bottomFooter-2cn&quot;]/div[@class=&quot;footer-paymentsLogo-CLu&quot;]</value>
      <webElementGuid>2f7c8574-0880-4a00-99eb-03cb2173fe9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/footer/div/div[3]/div</value>
      <webElementGuid>a4a43d26-1fad-48a3-a2bb-33b780ffbd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسترجاع و الاستبدال'])[1]/following::div[7]</value>
      <webElementGuid>20897c67-1b78-4cc5-b7d3-f46fc618ffc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سياسة الخصوصية'])[1]/following::div[7]</value>
      <webElementGuid>4b16f329-a9ae-4730-8b0e-ae6da4ef8abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Store'])[1]/preceding::div[9]</value>
      <webElementGuid>96ad1883-7824-457c-8f4c-48110d5d2303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Language'])[1]/preceding::div[12]</value>
      <webElementGuid>d9ac03b1-725c-4f55-a0df-dedc7d48e236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/div</value>
      <webElementGuid>35ed296d-0f9a-4fd9-959b-52b937c05412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
