<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>5aba414e-df8b-4bfd-9568-db1edb811391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.subscribePage-root-33l</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b86659d2-e910-4f86-922b-b1430ca2e17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subscribePage-root-33l</value>
      <webElementGuid>e962779f-03a5-473c-abd4-004a163008ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تابعنا عبر</value>
      <webElementGuid>99a7e8b2-9be8-43cb-bf60-7a1f6722d11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;subscribePage-root-33l&quot;]</value>
      <webElementGuid>3347baa3-9204-4b00-b97d-4299254e93b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[4]</value>
      <webElementGuid>b30c46d3-09e0-465b-a9f6-2fb1356d4064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأسعار شاملة الضريبة'])[1]/following::div[1]</value>
      <webElementGuid>8bba1f5e-2146-4a8f-b079-a11389acd809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='وسائل دفع آمنة'])[1]/following::div[3]</value>
      <webElementGuid>c40c7c0c-aadf-4342-9b7b-5fa6fbb06745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عجلان وإخوانه'])[1]/preceding::div[8]</value>
      <webElementGuid>95f6ae45-86e3-43eb-a348-41add1b2ce5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[4]</value>
      <webElementGuid>a23d29bb-60fc-4469-9de9-598d7a80f931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'تابعنا عبر' or . = 'تابعنا عبر')]</value>
      <webElementGuid>2f530ce2-1103-4748-9c04-93a3acf24e5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
