<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__footer-paymentsLogo-CLu</name>
   <tag></tag>
   <elementGuidId>8968260e-de6c-4d6d-82cc-3e160f312666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='footer-paymentsLogo-CLu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer-paymentsLogo-CLu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17469fa3-54b2-4345-b623-8126cf0c6cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-paymentsLogo-CLu</value>
      <webElementGuid>b7502b24-fbcf-4231-af84-d6fa9c4535eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/footer[@class=&quot;footer-root-39z&quot;]/div[@class=&quot;footer-main-1kk&quot;]/div[@class=&quot;footer-bottomFooter-2cn&quot;]/div[@class=&quot;footer-paymentsLogo-CLu&quot;]</value>
      <webElementGuid>7dda3954-0587-4507-848f-3394a4517500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/footer/div/div[3]/div</value>
      <webElementGuid>9ba1f406-8f0a-46db-8f28-617911e3d7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسترجاع و الاستبدال'])[1]/following::div[7]</value>
      <webElementGuid>a93968b2-4d9e-4669-9ea6-c600b29654ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سياسة الخصوصية'])[1]/following::div[7]</value>
      <webElementGuid>4a5daaab-c9a4-4bfe-bde7-3cd899bbf9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Store'])[1]/preceding::div[9]</value>
      <webElementGuid>6aad4688-53a9-44b6-ac13-b4b19449af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Language'])[1]/preceding::div[12]</value>
      <webElementGuid>ca4b10e2-4ca2-4192-b074-4bf9b5c3451c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[3]/div</value>
      <webElementGuid>c43cb61d-a2e0-4675-9cf8-41909ed957a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
