<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0  ()  113.85</name>
   <tag></tag>
   <elementGuidId>702354d6-2ec1-4070-90ac-cbd32b7b4ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slick-slide.slick-active.slick-current > div > div.productBlock-customItemNoSize-cyc.item-root-1Qt > div.item-container-FZs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-tabs-9']/div/div/div/div/div/div/div/div[13]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec362ebb-fa77-49d1-92b5-99e2659035a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-container-FZs</value>
      <webElementGuid>663799a7-e729-47ce-ac22-5e0fb24a882b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة</value>
      <webElementGuid>64ce62d9-0818-4826-abeb-1ec9bd44440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-9&quot;)/div[@class=&quot;tabProductBlock-tabItem-14y&quot;]/div[@class=&quot;productBlock-root-2Nd&quot;]/div[@class=&quot;sc-gtsrHT gfuSqG productBlock-wrapper-3JW&quot;]/div[@class=&quot;productBlock-slider-tok&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;productBlock-customItemNoSize-cyc item-root-1Qt&quot;]/div[@class=&quot;item-container-FZs&quot;]</value>
      <webElementGuid>7b2f7eb8-e29e-4f5f-bde7-cd04e6a2d240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-9']/div/div/div/div/div/div/div/div[13]/div/div/div</value>
      <webElementGuid>0a3db017-384e-4277-a83a-fcee6b0ae2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أضف إلى السلة'])[12]/following::div[5]</value>
      <webElementGuid>0bd52072-7bcc-4667-ac49-2bfd43314f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[12]/following::div[6]</value>
      <webElementGuid>ab769a34-8707-4d51-bfc2-d7d6e295cc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div</value>
      <webElementGuid>141a63a9-71f9-411a-9b3b-d4ed57df89ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة' or . = '0شماغ العجلان (البلاتيني) رجالي أحمر113.85 ر.سأضف إلى السلة')]</value>
      <webElementGuid>b0f7ff8d-2add-4662-9a01-0b055423c3a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
