<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>ffc62857-e04d-4711-b642-6ca774b87f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.productBlock-heading-9de</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'productBlock-containerTitle')]//h2[text()='تصفح العروض']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2760ae51-33cf-496c-8603-c81d1b5dde49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productBlock-heading-9de</value>
      <webElementGuid>1cf0e0ec-e061-46e9-b155-a919ed686072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تصفح العروض</value>
      <webElementGuid>7f15ccb4-7396-46c0-81c7-8c4c8de9bf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;cms-root-2Wa&quot;]/div[@class=&quot;productBlock-root-2Nd&quot;]/div[@class=&quot;productBlock-containerTitle-dw7&quot;]/h2[@class=&quot;productBlock-heading-9de&quot;]</value>
      <webElementGuid>58a9262c-4818-468f-be00-ab79e58c986d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[5]/div/h2</value>
      <webElementGuid>d963aaaa-48f0-44bb-9578-19a64dbc5c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أضف إلى السلة'])[22]/following::h2[1]</value>
      <webElementGuid>391d7c9b-ec17-4c15-82b3-4e7b9c6e130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[22]/following::h2[1]</value>
      <webElementGuid>4e8dec7a-59a8-4e94-a57b-53a359281ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شماغ بروجيه رجالي احمر شلش فيجن'])[1]/preceding::h2[1]</value>
      <webElementGuid>df32449a-baa8-4ab8-ac68-0caf33db436d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='غير متوفر بالمخزون'])[1]/preceding::h2[2]</value>
      <webElementGuid>9f635395-52b1-40b2-a356-732639ddac79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تصفح العروض']/parent::*</value>
      <webElementGuid>03fdaf19-25ff-4ad9-8c1c-03ca9419b59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h2</value>
      <webElementGuid>d7654104-7046-459e-9941-c473f4b906c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'تصفح العروض' or . = 'تصفح العروض')]</value>
      <webElementGuid>8499c889-e25c-44a0-800b-47525b341809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
