<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2__1</name>
   <tag></tag>
   <elementGuidId>73be9363-5df1-4fbd-946c-44b40a45184a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/h2[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>287c125a-a9f7-4507-97a5-488fb46cf770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnBanner-landingTitle-Y7b </value>
      <webElementGuid>93da2ba0-5d40-474a-b84c-b94b130a44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الأثواب</value>
      <webElementGuid>d63a08ab-3c59-41a7-b6e5-7b9fca919ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;cms-root-2Wa&quot;]/h2[@class=&quot;columnBanner-landingTitle-Y7b&quot;]</value>
      <webElementGuid>9472a1d6-2728-4655-9ddc-8df7eb0ba422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/h2[2]</value>
      <webElementGuid>6e2582c6-a120-4bdb-b39d-13613b59315b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أضف إلى السلة'])[70]/following::h2[1]</value>
      <webElementGuid>e4ff0344-5faa-456e-92d1-91e984c3c0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[70]/following::h2[1]</value>
      <webElementGuid>62603fe8-6538-44e4-97c1-e885fe73c58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ثوب دروش ابيض رجالي فلامنت سادة سادة قبة كيرف'])[1]/preceding::h2[1]</value>
      <webElementGuid>a9e27661-dee3-4c52-9f94-85c5c5e1987d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>4430d7d2-2d2f-4fee-af33-369233e97261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'الأثواب' or . = 'الأثواب')]</value>
      <webElementGuid>7450891c-8da9-4538-a074-a7b2a4a43b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
