<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2__1</name>
   <tag></tag>
   <elementGuidId>87febe9d-27ed-4c4b-971e-7b1b930bb76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/h2[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b6c37d4c-ee14-4747-85ed-a29b1425ca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnBanner-landingTitle-Y7b </value>
      <webElementGuid>a76dc921-0181-46e9-a6c0-59f253c406c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الأثواب</value>
      <webElementGuid>1a9dea91-ef94-4872-af76-cf7d7ea80af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;cms-root-2Wa&quot;]/h2[@class=&quot;columnBanner-landingTitle-Y7b&quot;]</value>
      <webElementGuid>cc8cac68-4f59-4fc2-99e7-6e864f6a0965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/h2[2]</value>
      <webElementGuid>4465e224-f493-4787-a56e-6ef5781d880e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أضف إلى السلة'])[70]/following::h2[1]</value>
      <webElementGuid>3c35cfad-63e6-4971-b90f-63630065d3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[70]/following::h2[1]</value>
      <webElementGuid>7279ec6f-7d6f-4c86-be26-07d561a39e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ثوب دروش ابيض رجالي فلامنت سادة سادة قبة كيرف'])[1]/preceding::h2[1]</value>
      <webElementGuid>46197bed-96aa-4018-ad7b-8666e33f5fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>b1dc8d49-ae6d-46b5-b8bf-9641b09a25a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'الأثواب' or . = 'الأثواب')]</value>
      <webElementGuid>d90c0c09-39b0-48f2-81af-20e543fb22f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
