<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__image-image-2gD image-loaded-SHk image_3b67db</name>
   <tag></tag>
   <elementGuidId>d20c5bad-355a-47e2-bd91-5dd29a850296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-image-2gD.image-loaded-SHk.image-loadedRtl-sS7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>988a1b41-c748-41ec-9290-0a10834cf3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9f4eb2cc-3ad1-458b-92dc-b53842dd0bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>a6c94f06-bf02-4e50-ad67-bb5451591a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-image-2gD image-loaded-SHk image-loadedRtl-sS7</value>
      <webElementGuid>5fadf7fd-dd13-4c88-bdcc-7c94279919a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>51ef2634-7175-4b91-918b-a22645075ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logo-8QT.png</value>
      <webElementGuid>c2ed06ac-6da9-4247-b829-e1d033f1d171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>e70cb102-1c31-4948-8d4a-b07110fbac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/header[@class=&quot;header-closed-2dE header-root-3ce&quot;]/div[@class=&quot;middleHeaderBar-root-3ns middleHeaderBar-close-2Ut middleHeaderBar-root-3ns&quot;]/div[@class=&quot;middleHeaderBar-content-_nW&quot;]/a[@class=&quot;middleHeaderBar-logoWrapper-1WY&quot;]/div[@class=&quot;image-root-Qpm
        image-container-_fN&quot;]/img[@class=&quot;image-image-2gD image-loaded-SHk image-loadedRtl-sS7&quot;]</value>
      <webElementGuid>dff194fa-ea04-46ba-82c8-64c1153fd62e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[2]/div/a/div/img[2]</value>
      <webElementGuid>7528a5e0-293c-4c33-b5a8-ad698963023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Logo'])[2]</value>
      <webElementGuid>99282541-7016-4a23-ac78-067e4f064c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>83e9a99f-04f8-4f17-a55a-95f9a2054d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo' and @src = '/logo-8QT.png']</value>
      <webElementGuid>4d0d64b3-26c5-4a0a-94af-bd05eaf1f4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
