<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms</name>
   <tag></tag>
   <elementGuidId>b0bea60c-1f1e-4a06-a12f-2376a6131b04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e810e97-02ff-403b-9dd1-87ca9339e0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a415b546-8020-4fbf-a90e-a2cddd65097c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>3d6dfb54-e606-40cd-a109-b42434379d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      <webElementGuid>db2d2802-a8bf-4b5c-9df9-a620484da2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>76d2dcc2-e9ea-402d-807e-32020bf180df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;556a1b66-0f54-4b9b-981e-8f8ae29a63a3&quot;)</value>
      <webElementGuid>8a11a058-3c63-483c-84e5-580fca63190d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      <webElementGuid>73ceed59-0043-4eb4-9e53-cd65e75b9d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>d960d259-67b5-46b7-a706-19c7e496a8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>a458890f-70b2-4ee3-9226-7cb682a97a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = '556a1b66-0f54-4b9b-981e-8f8ae29a63a3' and @name = 'acpTerms']</value>
      <webElementGuid>8942b37e-416e-4804-ac9e-699afde687a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
