<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phoneInputCustom-input-OnI</name>
   <tag></tag>
   <elementGuidId>5d190299-4505-483f-b53d-b8ba2247cebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>581492572</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.phoneInputCustom-input-OnI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e51ea6a1-1ef0-425b-a2c2-40986acd3bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>28b195d1-b043-4cf6-a58d-7713ce248c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>787ef102-f6f2-411b-ae37-260450a14674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phoneInputCustom-input-OnI</value>
      <webElementGuid>dfa0ee6c-55ee-45f8-8ff4-090c61ae1326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000 - 000 - 000</value>
      <webElementGuid>371e1b9b-b178-4bcf-8a7b-1d9cd229c2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>581 - 492 - 572</value>
      <webElementGuid>3aa6d411-abaf-4722-a11d-57cb8bb6511c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;phoneInputCustom-root-2RN&quot;]/div[@class=&quot;phoneInputCustom-control-3Qz phoneInputCustom-controlValid-2gS phoneInputCustom-controlFocus-F5X&quot;]/input[@class=&quot;phoneInputCustom-input-OnI&quot;]</value>
      <webElementGuid>3adf5608-ed58-491f-a274-3066333e399d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='581 - 492 - 572']</value>
      <webElementGuid>220da717-f7ab-4f8c-b4d1-a8c1a1e7e8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div/div/input</value>
      <webElementGuid>2328c624-d7ce-48cf-b2d7-ee4e874604b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c5cd710-4598-4e56-93b3-1379ae8e3893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '000 - 000 - 000']</value>
      <webElementGuid>3f569400-7c1f-4657-8123-7955bbb75b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
