<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phoneInputCustom-input-OnI</name>
   <tag></tag>
   <elementGuidId>44a68ad4-d7b9-4923-b7b5-887d3c2448bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.phoneInputCustom-input-OnI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>581492572</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0ebd820-a932-4e69-8039-3754face970d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9afd59ec-3642-40b9-9ad0-520d4e3ee845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2feb78d6-6a4f-4827-84b4-54369cc53cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phoneInputCustom-input-OnI</value>
      <webElementGuid>a2b7105c-e201-4795-a757-53cbb771f6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000 - 000 - 000</value>
      <webElementGuid>0cc721ee-0977-4b0d-a636-b09918f25755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>581 - 492 - 572</value>
      <webElementGuid>75b539bc-8cc8-43a6-9708-3a797299eb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;phoneInputCustom-root-2RN&quot;]/div[@class=&quot;phoneInputCustom-control-3Qz phoneInputCustom-controlValid-2gS phoneInputCustom-controlFocus-F5X&quot;]/input[@class=&quot;phoneInputCustom-input-OnI&quot;]</value>
      <webElementGuid>b849a0fb-8d9d-47a1-bc0f-9f8ce0b8d332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='581 - 492 - 572']</value>
      <webElementGuid>79a2d74d-4ac2-4418-8f1b-6d782fedf03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div/div/input</value>
      <webElementGuid>e52e1553-37b9-4797-b236-f5005a027941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>20dbe886-56aa-49a0-9525-0e5593695468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '000 - 000 - 000']</value>
      <webElementGuid>2dfac326-f008-45f5-b6ec-677590341337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
