<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms</name>
   <tag></tag>
   <elementGuidId>dd35faf5-295e-42e3-a67d-c82f16a251ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0830303a-050d-4ecd-8103-29f8505feae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ab3f3b53-ea75-43ef-94ee-2ee0fddf73e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>cd58e8f6-f37a-49fc-904e-9a2eb4b40ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      <webElementGuid>4c5e9179-f035-44e9-87a4-d29153da99c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>017e2a45-d682-4318-ac4b-44693578ce85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;556a1b66-0f54-4b9b-981e-8f8ae29a63a3&quot;)</value>
      <webElementGuid>8b3715b7-491d-4be5-82e6-e69ca2b9ceb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      <webElementGuid>93c8f7ed-7ac0-43e1-8d28-420f0840e38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>1f5c6156-12dc-4c9a-8e86-d44a1552bf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>fc797d97-1012-4678-a47d-19c9de1d556c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = '556a1b66-0f54-4b9b-981e-8f8ae29a63a3' and @name = 'acpTerms']</value>
      <webElementGuid>da97afc8-793d-4485-b518-b505ed9e0860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
