<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms</name>
   <tag></tag>
   <elementGuidId>604322ca-0ef1-4e67-8486-7eaa69bde255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e84428-2445-4d14-b2b5-e0ab2c5d10d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e8dd4cc8-0c22-4ba0-823c-e7b96bc5062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>4242df67-d2ae-4b2e-8aeb-05c6fccae51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>556a1b66-0f54-4b9b-981e-8f8ae29a63a3</value>
      <webElementGuid>fbec9975-9ef3-4968-96b9-d3f1fec71ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>6bf37a21-6bf8-46d5-a87c-4285e46b6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;556a1b66-0f54-4b9b-981e-8f8ae29a63a3&quot;)</value>
      <webElementGuid>5d65bc65-9123-4cb8-b28f-0c706ead1b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='556a1b66-0f54-4b9b-981e-8f8ae29a63a3']</value>
      <webElementGuid>c943a252-6839-43ee-90f6-8158d59d1d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>55422270-11b6-496a-9778-07463b983984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>639c1f19-90f7-4fca-b693-6eb36e3551fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = '556a1b66-0f54-4b9b-981e-8f8ae29a63a3' and @name = 'acpTerms']</value>
      <webElementGuid>05ff6c4d-bee6-4c7b-b0f4-ecaf03ba8b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
