<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms_1</name>
   <tag></tag>
   <elementGuidId>db5633c1-5715-44e8-a71a-91ca40b01e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edda4719-a791-484c-a7fd-344102d8e7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7d9e1e6-c266-4a79-b60f-023b7015af04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>1d0ae775-0186-4ba1-9c24-e47cd449df2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      <webElementGuid>7603ffe5-250c-437b-9f5d-83120ea6bb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>792c68a4-3512-465a-83f8-c5792ec03b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc2b9ee1-8760-4c21-8869-fa31031d207d&quot;)</value>
      <webElementGuid>e3e85a46-8f31-4d81-845b-702080ac0f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      <webElementGuid>9f9b8eb7-1eca-43e9-ac68-c29595cd588a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>26b306ae-dc02-4293-9513-b52aba26ba09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>9985ced9-2186-435a-99d6-19a4dd505ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'dc2b9ee1-8760-4c21-8869-fa31031d207d' and @name = 'acpTerms']</value>
      <webElementGuid>fdbe84aa-4ea3-4ca7-9852-3fd09b970ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
