<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phoneInputCustom-input-OnI</name>
   <tag></tag>
   <elementGuidId>aa177a9e-443c-4662-a6f5-84816982114c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.phoneInputCustom-input-OnI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>581492572</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>213c470d-c3a1-49ac-9ffc-5972759cbaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>454b0ded-a34c-4f77-8ee0-a973bde6383c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>68ac93b5-6444-4d7c-9d11-8ea8201ded38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phoneInputCustom-input-OnI</value>
      <webElementGuid>311d0fa2-8795-4586-bafb-28a31cc459b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000 - 000 - 000</value>
      <webElementGuid>21c1309d-4d92-4758-a3d3-dd7027bb12e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>581 - 492 - 572</value>
      <webElementGuid>8c4cf94d-f80d-4e5c-a6f2-cb6e2fab1dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;phoneInputCustom-root-2RN&quot;]/div[@class=&quot;phoneInputCustom-control-3Qz phoneInputCustom-controlValid-2gS phoneInputCustom-controlFocus-F5X&quot;]/input[@class=&quot;phoneInputCustom-input-OnI&quot;]</value>
      <webElementGuid>51163d00-8dd0-47b4-8c0a-2f72d772dee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='581 - 492 - 572']</value>
      <webElementGuid>ae63520b-f0a0-40f8-99a8-43b049f00b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div/div/input</value>
      <webElementGuid>ddc5dbc6-2817-4af2-8c8d-cf91d846c215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4a086d9-b455-4488-b731-8b9781c16855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '000 - 000 - 000']</value>
      <webElementGuid>6951f9de-05e8-4d64-a949-eee6d27526f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
