<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms_1</name>
   <tag></tag>
   <elementGuidId>b370f632-fdee-4ba8-abe9-198996d4b4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>964206c2-306d-46dc-b15b-a672e6a20768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a236d967-491e-4212-b36c-457045504f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>8d3cf72f-8985-4c05-91c6-adfc98855641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      <webElementGuid>8d46f4a7-bf22-49d7-841a-4c133e751a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>9bfc091f-ac4f-4f91-911b-9c1efc455c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc2b9ee1-8760-4c21-8869-fa31031d207d&quot;)</value>
      <webElementGuid>30890764-9966-4b91-b7dc-d22c40e3c874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      <webElementGuid>2829728f-2eac-4479-b765-9b0ef7b5ea8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>8ff8c796-9736-4f4e-be28-5c2f65cf7500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b7adeb5f-abef-476c-ac0d-e6acc3a16ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'dc2b9ee1-8760-4c21-8869-fa31031d207d' and @name = 'acpTerms']</value>
      <webElementGuid>b6cc759c-ad31-41d3-8459-6418fa3fb367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
