<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acpTerms_1</name>
   <tag></tag>
   <elementGuidId>e6ed3515-0bed-48ea-9df7-7398a8806c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4230ed3-b3fc-41f4-83e4-9eebd85cbf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bd1db704-7942-46e5-a57a-a43d74dca5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input-2Tv</value>
      <webElementGuid>68c9100e-3d75-446d-830d-67ee694d03e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dc2b9ee1-8760-4c21-8869-fa31031d207d</value>
      <webElementGuid>bfa00618-e005-4f2a-8c5c-008c0d51d142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acpTerms</value>
      <webElementGuid>e59ea31b-a6a9-49a8-9cfa-8cd9c9a1cb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dc2b9ee1-8760-4c21-8869-fa31031d207d&quot;)</value>
      <webElementGuid>8b72b453-6263-4d45-b4c2-09ffaf21780e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dc2b9ee1-8760-4c21-8869-fa31031d207d']</value>
      <webElementGuid>d2e34ac2-708e-4e05-86bd-6f0f40831d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/label/input</value>
      <webElementGuid>1845c400-7d62-4287-a8bc-f7e60ade2e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>556e6604-e2f0-45eb-9e9d-0679eef597bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'dc2b9ee1-8760-4c21-8869-fa31031d207d' and @name = 'acpTerms']</value>
      <webElementGuid>d266cc11-a075-47ce-a043-2c17bf093f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
