<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>e8323668-392d-4b43-b91e-8a48ed603963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.button-content-3AN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d688ff9-7486-4702-9749-352076cd40bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-content-3AN</value>
      <webElementGuid>555efe52-05f3-42b3-9a0f-481895ca4618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>c44cf750-3d08-406a-8df0-c8b2d6e33a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;signIn-blockBtnSubmit-1wk&quot;]/button[@class=&quot;signIn-submitButton-mYZ button-root_highPriority-qp_ button-root-2JQ clickable-root-1G6&quot;]/span[@class=&quot;button-content-3AN&quot;]</value>
      <webElementGuid>a288b6e1-772b-43e3-ac7a-b9f163cd635d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      <webElementGuid>fd819862-44ff-46df-b8c2-a1b06d0f990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ادخل رقم الجوال، وستصلك رسالة تحتوي على رمز تحقق'])[1]/following::span[1]</value>
      <webElementGuid>8da05baf-bde7-48ce-a933-716eace715e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول'])[1]/following::span[1]</value>
      <webElementGuid>f0c70cda-4866-4b30-b9da-967174e22f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لقد قرأت الشروط والأحكام، وأوافق عليها'])[1]/preceding::span[2]</value>
      <webElementGuid>f5f628ca-bca8-4240-9e8c-53472d5ce6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول بالبريد الالكتروني'])[1]/preceding::span[3]</value>
      <webElementGuid>6eef957f-402c-4f15-9683-2755f0cc9f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button/span</value>
      <webElementGuid>eada58e9-e2b9-4b2e-b88b-da4d8e680b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>7e08800d-ac8c-4efe-827f-03c17d7914aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
