<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>5fe298b7-8c2f-4dec-922a-12260a0e93d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button-content-3AN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4b2a07b-0612-4165-8921-0d38a5ffea4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-content-3AN</value>
      <webElementGuid>7342cd99-7b4f-4dc2-bfcb-0aba81913d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>84c8519d-3d6a-45eb-840c-6bef9c656dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;signIn-blockBtnSubmit-1wk&quot;]/button[@class=&quot;signIn-submitButton-mYZ button-root_highPriority-qp_ button-root-2JQ clickable-root-1G6&quot;]/span[@class=&quot;button-content-3AN&quot;]</value>
      <webElementGuid>b6e2c556-e243-4d12-88c9-33c1dc3cf2d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      <webElementGuid>69971590-64d6-4338-8049-c1a5f29dd916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ادخل رقم الجوال، وستصلك رسالة تحتوي على رمز تحقق'])[1]/following::span[1]</value>
      <webElementGuid>027f4d1b-8761-4476-8c7d-9d73bca8980e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول'])[1]/following::span[1]</value>
      <webElementGuid>66c7a46b-eda8-4732-8e82-85b0f31efb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لقد قرأت الشروط والأحكام، وأوافق عليها'])[1]/preceding::span[2]</value>
      <webElementGuid>679f0b8c-1937-4195-bf29-8b1e7e1127ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول بالبريد الالكتروني'])[1]/preceding::span[3]</value>
      <webElementGuid>9c8005d0-6986-40e1-8452-af09308747bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button/span</value>
      <webElementGuid>52604597-677a-489d-a9e0-d2e49dccfd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>b872ac98-f7fc-408c-a045-db4f2303104b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
