<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>d44466f8-64d0-4edc-bfc2-753715529da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button-content-3AN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e450e1eb-6dba-40ad-8a9b-a41f8239cf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-content-3AN</value>
      <webElementGuid>245cf30c-2f92-4993-86a1-ef0fab0ff66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل الدخول</value>
      <webElementGuid>32f9ae1a-eb81-4915-80c6-2c08d2ff3fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2iR&quot;]/div[@class=&quot;main-page-279&quot;]/div[@class=&quot;signInPage-root-3ap&quot;]/div[@class=&quot;signInPage-formSignUp-3F5&quot;]/form[1]/div[@class=&quot;signIn-container-3m2&quot;]/div[@class=&quot;signIn-blockBtnSubmit-1wk&quot;]/button[@class=&quot;signIn-submitButton-mYZ button-root_highPriority-qp_ button-root-2JQ clickable-root-1G6&quot;]/span[@class=&quot;button-content-3AN&quot;]</value>
      <webElementGuid>90066e37-8891-48de-8559-679cedd93e26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/form/div/div[2]/button/span</value>
      <webElementGuid>f015809b-1272-4984-b206-f091a003c376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ادخل رقم الجوال، وستصلك رسالة تحتوي على رمز تحقق'])[1]/following::span[1]</value>
      <webElementGuid>3962c955-aa2d-4ee5-9a46-b5c90ea8b1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول'])[1]/following::span[1]</value>
      <webElementGuid>92ad8a99-b686-48d2-96b9-655542f14222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لقد قرأت الشروط والأحكام، وأوافق عليها'])[1]/preceding::span[2]</value>
      <webElementGuid>ca465abb-ae00-4602-a9a3-263c28ed14b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تسجيل الدخول بالبريد الالكتروني'])[1]/preceding::span[3]</value>
      <webElementGuid>620d8ad8-c1c6-43b1-b18d-8b6bfae132b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button/span</value>
      <webElementGuid>eadca178-549b-48ae-a6ec-6505e5ac76f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'تسجيل الدخول' or . = 'تسجيل الدخول')]</value>
      <webElementGuid>7ae7dbd4-19eb-47d6-b394-1683bd947d3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
