<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product_Price</name>
   <tag></tag>
   <elementGuidId>ea102803-58a9-4c46-84be-5d69029b36ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[contains(@class,&quot;productFullDetail-productPrice-&quot;)]//div[1]//div//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
