<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipmentMethodsList</name>
   <tag></tag>
   <elementGuidId>7c381882-a7d1-43a2-a383-d6744898d620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,&quot;shippingMethod-shippingMethodBody-&quot;)]</value>
      <webElementGuid>f8bbf987-45dd-44e0-93fe-52565bc274ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
