<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filters</name>
   <tag></tag>
   <elementGuidId>c995a52f-9b80-4fd8-9a03-adc87093268d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Filters' or . = 'Filters')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.action-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc0850a7-99e7-4097-abaa-5e5da044d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-default</value>
      <webElementGuid>0fd8cb71-bd69-47ac-b349-24b738010a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>grid-filter-expand</value>
      <webElementGuid>eccaf81c-bf72-4114-a9f5-7d7dd759c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: {_active: hasVisible() &amp;&amp; $collapsible.opened()}, disable: !hasVisible(), i18n: 'Filters', toggleCollapsible</value>
      <webElementGuid>b6fe6c7d-b5c9-448d-961c-98afa39ca6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>39ee1685-ec0c-4a93-8f6b-66c56e8295cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;admin__data-grid-outer-wrap&quot;]/div[@class=&quot;admin__data-grid-header&quot;]/div[@class=&quot;admin__data-grid-header-row&quot;]/div[@class=&quot;data-grid-filters-actions-wrap&quot;]/div[@class=&quot;data-grid-filters-action-wrap&quot;]/button[@class=&quot;action-default&quot;]</value>
      <webElementGuid>52056bae-ebc9-4834-9548-d8c0448b700b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>49829a28-9d09-4bd2-812e-c0104fcf3786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[7]/following::button[1]</value>
      <webElementGuid>641d7d6e-d4e2-451d-b0ef-8bbc504436e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[2]</value>
      <webElementGuid>6228c75d-67ab-4915-bd70-71619ab679e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active filters:'])[1]/preceding::button[1]</value>
      <webElementGuid>31cdbf68-50a9-4459-a130-974ddafa561e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear all'])[1]/preceding::button[1]</value>
      <webElementGuid>090b02f8-9da0-4f5a-8d25-7cf087049be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>4a407f46-daab-430c-ad46-70f674808ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>340c9e40-f43b-43e5-8200-df3d3d6f91b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>6a5127fa-1125-4ca0-a8c9-fbcd4d668b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
