<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CategoriesL2</name>
   <tag></tag>
   <elementGuidId>f7c95dd0-e670-450a-a0fb-ddae8da0796e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;promobanner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;promobanner&quot;]</value>
      <webElementGuid>23ae036e-479c-49d8-b6df-810a548d32b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
