<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MailChimpIFrame</name>
   <tag></tag>
   <elementGuidId>97fdfd3d-11d2-4956-88da-dc45ac067c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@data-dojo-attach-point=&quot;iframeModalContainer&quot;]</value>
      <webElementGuid>325509f3-2e0c-46c3-86f5-2ecf966ee1d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
