<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalAmount</name>
   <tag></tag>
   <elementGuidId>aecacf7d-dce1-42af-b6bf-f1abc21a2729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()=&quot;المجموع&quot;]//following-sibling::span[contains(@class,&quot;priceSummary-totalPriceFull&quot;)][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
